# Generated by Django 6.1 on 2026-08-11 17:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'db_table': 'rag_conversations',
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512, verbose_name='name')),
                ('source_type', models.CharField(choices=[('FILE', 'File'), ('URL', 'URL'), ('SITEMAP', 'Sitemap'), ('CONFLUENCE', 'Confluence')], default='FILE', max_length=16, verbose_name='source type')),
                ('source_uri', models.TextField(blank=True, default='', verbose_name='source URI')),
                ('status', models.CharField(choices=[('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('ERROR', 'Error')], default='UPLOADING', max_length=16, verbose_name='status')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('storage_key', models.CharField(blank=True, default='', max_length=1024, verbose_name='storage key')),
                ('content_type', models.CharField(blank=True, default='', max_length=255, verbose_name='MIME type')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='size in bytes')),
                ('checksum', models.CharField(blank=True, default='', max_length=64, verbose_name='sha256')),
                ('chunk_count', models.PositiveIntegerField(default=0, verbose_name='chunk count')),
                ('task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='celery task id')),
                ('source_options', models.JSONField(blank=True, default=dict, verbose_name='source options')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'db_table': 'rag_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='content hash')),
                ('content', models.TextField(verbose_name='content')),
                ('content_type', models.CharField(choices=[('TEXT', 'Text'), ('TABLE', 'Table'), ('IMAGE', 'Image'), ('SUMMARY', 'Summary')], default='TEXT', max_length=16, verbose_name='content type')),
                ('page', models.CharField(blank=True, default='', max_length=255, verbose_name='page')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.document', verbose_name='document')),
            ],
            options={
                'verbose_name': 'chunk',
                'verbose_name_plural': 'chunks',
                'db_table': 'rag_chunks',
                'ordering': ['document', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16, verbose_name='role')),
                ('content', models.TextField(verbose_name='content')),
                ('citations', models.JSONField(blank=True, default=list, verbose_name='citations')),
                ('finish_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='finish reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rag.conversation', verbose_name='conversation')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'db_table': 'rag_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['owner', '-modified_at'], name='rag_convers_owner_i_499ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'status'], name='rag_documen_owner_i_80fd2c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', '-created_at'], name='rag_documen_owner_i_43b3b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_document_per_owner'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['document', 'content_type'], name='rag_chunks_documen_b13f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='rag_message_convers_023670_idx'),
        ),
    ]
