# Generated by Django 6.1 on 2026-08-22 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages_detected', models.PositiveIntegerField(default=0, verbose_name='pages detected')),
                ('pages_with_text', models.PositiveIntegerField(default=0, verbose_name='pages with text')),
                ('pages_without_text', models.PositiveIntegerField(default=0, verbose_name='pages without text')),
                ('total_extracted_chars', models.PositiveIntegerField(default=0, verbose_name='total extracted characters')),
                ('avg_chars_per_page', models.FloatField(default=0.0, verbose_name='average characters per page')),
                ('extractor_used', models.CharField(blank=True, default='', max_length=255, verbose_name='extractor used')),
                ('ocr_used', models.BooleanField(default=False, verbose_name='OCR used')),
                ('ocr_language', models.CharField(blank=True, default='', max_length=64, verbose_name='OCR language')),
                ('text_chunks', models.PositiveIntegerField(default=0, verbose_name='text chunks')),
                ('table_chunks', models.PositiveIntegerField(default=0, verbose_name='table chunks')),
                ('image_chunks', models.PositiveIntegerField(default=0, verbose_name='image chunks')),
                ('summary_chunks', models.PositiveIntegerField(default=0, verbose_name='summary chunks')),
                ('failed_summaries', models.PositiveIntegerField(default=0, verbose_name='failed summaries')),
                ('embedding_status', models.CharField(blank=True, default='', max_length=32, verbose_name='embedding status')),
                ('vector_upload_status', models.CharField(blank=True, default='', max_length=32, verbose_name='vector upload status')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='warnings')),
                ('quality_score', models.CharField(choices=[('GOOD', 'Good'), ('WARNING', 'Warning'), ('BAD', 'Bad')], default='WARNING', max_length=16, verbose_name='quality score')),
                ('ingestion_duration_seconds', models.FloatField(default=0.0, verbose_name='ingestion duration seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_reports', to='rag.document', verbose_name='document')),
            ],
            options={
                'verbose_name': 'ingestion report',
                'verbose_name_plural': 'ingestion reports',
                'db_table': 'rag_ingestion_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='last_ingestion_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rag.ingestionreport', verbose_name='last ingestion report'),
        ),
        migrations.AddIndex(
            model_name='ingestionreport',
            index=models.Index(fields=['document', '-created_at'], name='rag_ingesti_documen_548c90_idx'),
        ),
    ]
