# Generated by Django 6.1 on 2026-08-22 16:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_add_ingestion_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('DOCUMENT_UPLOAD', 'Document Upload'), ('DOCUMENT_REINDEX', 'Document Reindex'), ('DOCUMENT_DELETE', 'Document Delete'), ('QUERY', 'Query'), ('ADMIN_ACTION', 'Admin Action')], max_length=32, verbose_name='action')),
                ('resource_type', models.CharField(blank=True, default='', max_length=64, verbose_name='resource type')),
                ('resource_id', models.CharField(blank=True, default='', max_length=255, verbose_name='resource ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'db_table': 'rag_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='rag_audit_l_actor_i_c40119_idx'), models.Index(fields=['action', '-created_at'], name='rag_audit_l_action_29c71b_idx')],
            },
        ),
    ]
