# Generated by Django 5.1 on 2026-08-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_user_managers"),
        ("rag", "0005_organizations"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation", models.CharField(max_length=32, verbose_name="operation")),
                ("model", models.CharField(max_length=128, verbose_name="model")),
                (
                    "prompt_tokens",
                    models.PositiveIntegerField(default=0, verbose_name="prompt tokens"),
                ),
                (
                    "completion_tokens",
                    models.PositiveIntegerField(default=0, verbose_name="completion tokens"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage",
                        to="api.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "usage record",
                "verbose_name_plural": "usage records",
                "db_table": "rag_usage",
            },
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["organization", "-created_at"], name="rag_usage_organiz_9c0ed2_idx"
            ),
        ),
    ]
