# Generated by Django 5.1 on 2026-08-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0006_usagerecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPLOADING", "Uploading"),
                    ("PROCESSING", "Processing"),
                    ("ENRICHING", "Enriching"),
                    ("READY", "Ready"),
                    ("ERROR", "Error"),
                ],
                default="UPLOADING",
                max_length=16,
                verbose_name="status",
            ),
        ),
    ]
